[colors]
background = #292c3c
background-alt = #414559
foreground = #c6d0f5
primary = #8caaee
accent = #ca9ee6
warning = #e5c890
alert = #e78284
success = #a6d189
disabled = #737994

[bar/main]
; Tells the bar to use monitor passed by the launch script
monitor = ${env:MONITOR:}

; Full width, but use transparent borders to create "floating" gap
width = 100%
height = 24pt
radius = 6

; Pixel perfect gaps (adjust to match)
border-left-size = 12pt 
border-right-size = 12pt 
border-top-size = 2pt
border-bottom-size = 0pt
border-color = #00000000

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 2
padding-right = 2
module-margin = 1

font-0 = "JetBrainsMono Nerd Font:size=10;3"
font-1 = "JetBrainsMono Nerd Font:size=12;3"

modules-left = xworkspaces xwindow
modules-right = weather fs memory cpu temperature wlan vpn time bluetooth pulseaudio tlp-status battery systray shutdown_menu

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/systray]
type = internal/tray
tray-spacing = 8pt
tray-background = ${colors.background}

; --- NATIVE POLYBAR MODULES ---

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true
icon-default = 󰝦
format = <label-state>
label-active = 󰝥
label-active-foreground = ${colors.accent}
label-active-padding = 1
label-occupied = 󰝦
label-occupied-foreground = ${colors.disabled}
label-occupied-padding = 1
label-empty = ""

[module/xwindow]
type = internal/xwindow
label = %title:0:50:...%
label-foreground = ${colors.disabled}

[module/fs]
type = internal/fs
mount-0 = /
interval = 180
format-mounted = <label-mounted>
format-mounted-prefix = "󰋊 "
format-mounted-prefix-foreground = ${colors.primary}
label-mounted = %free%

[module/memory]
type = internal/memory
interval = 5
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.accent}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 3
format-prefix = "󰻠 "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/temperature]
type = internal/temperature
interval = 5
thermal-zone = 0
warn-temperature = 75
format = <ramp> <label>
format-warn = <ramp> <label-warn>
label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.alert}
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.warning}

[module/wlan]
type = internal/network
interface-type = wireless
interval = 5
format-connected = <ramp-signal> <label-connected>
label-connected = %essid% 󰁅 %downspeed%
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
ramp-signal-foreground = ${colors.primary}
label-disconnected = 󰤭
label-disconnected-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-foreground = ${colors.accent}
label-muted = 󰖁 Muted
label-muted-foreground = ${colors.disabled}
click-right = pavucontrol

[module/battery]
type = internal/battery
full-at = 98
low-at = 20
battery = BAT0
adapter = AC
poll-interval = 30
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
label-charging = %percentage%%
label-discharging = %percentage%%
ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁾
ramp-capacity-2 = 󰁹
ramp-capacity-foreground = ${colors.success}
animation-charging-0 = 󰢜
animation-charging-1 = 󰂆
animation-charging-2 = 󰂇
animation-charging-foreground = ${colors.warning}

[module/time]
type = internal/date
interval = 1
time = "󰥔 %H:%M"
date = "󰃭 %a, %d %b"
label = %date%  %time%
label-foreground = ${colors.foreground}

; --- CUSTOM SCRIPTS ---

[module/weather]
type = custom/script
exec = ~/.config/i3/scripts/openweather-city
interval = 3600
format-foreground = ${colors.primary}

[module/vpn]
type = custom/script
exec = ~/.config/i3/scripts/forticlient
interval = 10
format-foreground = ${colors.accent}

[module/bluetooth]
type = custom/script
exec = $HOME/.config/i3/scripts/bt-status
interval = 5
format-foreground = ${colors.primary}
click-left = kitty -e bluetui

[module/tlp-status]
type = custom/script
exec = ~/.config/i3/scripts/tlp-status
interval = 5
format-foreground = ${colors.warning}

[module/shutdown_menu]
type = custom/text
format = "󰐥"
format-foreground = ${colors.alert}
click-left = ~/.config/i3/scripts/powermenu
